//
//  CardMetaData.swift
//  Everything Magic
//
//  Created by Spencer McWilliams on 10/5/15.
//  Copyright © 2015 Spencer McWilliams. All rights reserved.
//

import Foundation

public class CardMetaData {
    public static let types: [String] = [
        "-",
        "artifact",
        "conspiracy",
        "creature",
        "enchantment",
        "instant",
        "land",
        "phenomenon",
        "plane",
        "planeswalker",
        "scheme",
        "sorcery",
        "tribal",
        "vanguard"
    ]
    public static let subtypes: [String] = [
        "-",
        "advisor",
        "ajani",
        "alara",
        "ally",
        "angel",
        "antelope",
        "ape",
        "arcane",
        "archer",
        "archon",
        "arkhos",
        "artificer",
        "ashiok",
        "assassin",
        "assembly-worker",
        "atog",
        "aura",
        "aurochs",
        "avatar",
        "azgol",
        "badger",
        "barbarian",
        "basilisk",
        "bat",
        "bear",
        "beast",
        "beeble",
        "belenon",
        "berserker",
        "bird",
        "boar",
        "bolas",
        "bolas’s meditation realm",
        "bringer",
        "brushwagg",
        "camel",
        "carrier",
        "cat",
        "centaur",
        "cephalid",
        "chandra",
        "chicken",
        "chimera",
        "cleric",
        "cockatrice",
        "construct",
        "crab",
        "crocodile",
        "curse",
        "cyclops",
        "dack",
        "daretti",
        "dauthi",
        "demon",
        "desert",
        "devil",
        "djinn",
        "dominaria",
        "domri",
        "dragon",
        "drake",
        "dreadnought",
        "drone",
        "druid",
        "dryad",
        "dwarf",
        "efreet",
        "elder",
        "eldrazi",
        "elemental",
        "elephant",
        "elf",
        "elk",
        "elspeth",
        "equilor",
        "equipment",
        "ergamon",
        "eye",
        "fabacin",
        "faerie",
        "ferret",
        "fish",
        "flagbearer",
        "forest",
        "fortification",
        "fox",
        "freyalise",
        "frog",
        "fungus",
        "gargoyle",
        "garruk",
        "gate",
        "giant",
        "gideon",
        "gnome",
        "goat",
        "goblin",
        "god",
        "golem",
        "gorgon",
        "gremlin",
        "griffin",
        "hag",
        "harpy",
        "hellion",
        "hippo",
        "hippogriff",
        "homarid",
        "homunculus",
        "horror",
        "horse",
        "hound",
        "human",
        "hydra",
        "hyena",
        "illusion",
        "imp",
        "incarnation",
        "innistrad",
        "insect",
        "iquatana",
        "ir",
        "island",
        "jace",
        "jellyfish",
        "juggernaut",
        "kaldheim",
        "kamigawa",
        "karn",
        "kavu",
        "kephalai",
        "kiora",
        "kirin",
        "kithkin",
        "knight",
        "kobold",
        "kolbahan",
        "kor",
        "koth",
        "kraken",
        "kyneth",
        "lair",
        "lamia",
        "lammasu",
        "leech",
        "legend",
        "leviathan",
        "lhurgoyf",
        "licid",
        "liliana",
        "lizard",
        "locus",
        "lorwyn",
        "manticore",
        "masticore",
        "mercadia",
        "mercenary",
        "merfolk",
        "metathran",
        "mine",
        "minion",
        "minotaur",
        "mirrodin",
        "moag",
        "monger",
        "mongoose",
        "mongseng",
        "monk",
        "moonfolk",
        "mountain",
        "muraganda",
        "mutant",
        "myr",
        "mystic",
        "naga",
        "nahiri",
        "narset",
        "nautilus",
        "nephilim",
        "new phyrexia",
        "nightmare",
        "nightstalker",
        "ninja",
        "nissa",
        "nixilis",
        "noggle",
        "nomad",
        "nymph",
        "octopus",
        "ogre",
        "ooze",
        "orc",
        "orgg",
        "ouphe",
        "ox",
        "oyster",
        "pegasus",
        "pest",
        "phelddagrif",
        "phoenix",
        "phyrexia",
        "pirate",
        "plains",
        "plant",
        "power-plant",
        "praetor",
        "processor",
        "rabbit",
        "rabiah",
        "ral",
        "rat",
        "rath",
        "ravnica",
        "rebel",
        "regatha",
        "rhino",
        "rigger",
        "rogue",
        "sable",
        "salamander",
        "samurai",
        "saproling",
        "sarkhan",
        "satyr",
        "scarecrow",
        "scorpion",
        "scout",
        "segovia",
        "serpent",
        "serra’s realm",
        "shade",
        "shadowmoor",
        "shaman",
        "shandalar",
        "shapeshifter",
        "sheep",
        "shrine",
        "siren",
        "skeleton",
        "slith",
        "sliver",
        "slug",
        "snake",
        "soldier",
        "soltari",
        "sorin",
        "spawn",
        "specter",
        "spellshaper",
        "sphinx",
        "spider",
        "spike",
        "spirit",
        "sponge",
        "squid",
        "squirrel",
        "starfish",
        "surrakar",
        "swamp",
        "tamiyo",
        "teferi",
        "tezzeret",
        "thalakos",
        "thopter",
        "thrull",
        "tibalt",
        "tower",
        "trap",
        "treefolk",
        "troll",
        "turtle",
        "ugin",
        "ulgrotha",
        "unicorn",
        "urza’s",
        "valla",
        "vampire",
        "vedalken",
        "venser",
        "viashino",
        "volver",
        "vraska",
        "vryn",
        "wall",
        "warrior",
        "weird",
        "werewolf",
        "whale",
        "wildfire",
        "wizard",
        "wolf",
        "wolverine",
        "wombat",
        "worm",
        "wraith",
        "wurm",
        "xenagos",
        "xerex",
        "yeti",
        "zendikar",
        "zombie",
        "zubera"
    ]
    
    public static let supertypes: [String] = [
        "-",
        "basic",
        "legendary",
        "ongoing",
        "snow",
        "world"
    ]
    
    public static var sets = [
        "-": "-",
        "15th Anniversary" : "p15A",
        "Alara Reborn" : "ARB",
        "Alliances" : "ALL",
        "Anthologies" : "ATH",
        "Antiquities" : "ATQ",
        "Apocalypse" : "APC",
        "Arabian Nights" : "ARN",
        "Archenemy" : "ARC",
        "Arena League" : "pARL",
        "Asia Pacific Land Program" : "pALP",
        "Avacyn Restored" : "AVR",
        "Battle for Zendikar" : "BFZ",
        "Battle Royale Box Set" : "BRB",
        "Beatdown Box Set" : "BTD",
        "Betrayers of Kamigawa" : "BOK",
        "Born of the Gods" : "BNG",
        "Celebration" : "pCEL",
        "Champions of Kamigawa" : "CHK",
        "Champs and States" : "pCMP",
        "Chronicles" : "CHR",
        "Clash Pack" : "CPK",
        "Classic Sixth Edition" : "6ED",
        "Coldsnap" : "CSP",
        "Coldsnap Theme Decks" : "CST",
        "Collector's Edition" : "CED",
        "Commander 2013 Edition" : "C13",
        "Commander 2014" : "C14",
        "Commander 2015" : "C15",
        "Commander's Arsenal" : "CM1",
        "Conflux" : "CON",
        "Dark Ascension" : "DKA",
        "Darksteel" : "DST",
        "Deckmasters" : "DKM",
        "Dissension" : "DIS",
        "Dragon Con" : "pDRC",
        "Dragon's Maze" : "DGM",
        "Dragons of Tarkir" : "DTK",
        "Duel Decks: Ajani vs. Nicol Bolas" : "DDH",
        "Duel Decks Anthology, Divine vs. Demonic" : "DD3_DVD",
        "Duel Decks Anthology, Elves vs. Goblins" : "DD3_EVG",
        "Duel Decks Anthology, Garruk vs. Liliana" : "DD3_GVL",
        "Duel Decks Anthology, Jace vs. Chandra" : "DD3_JVC",
        "Duel Decks: Divine vs. Demonic" : "DDC",
        "Duel Decks: Elspeth vs. Kiora" : "DDO",
        "Duel Decks: Elspeth vs. Tezzeret" : "DDF",
        "Duel Decks: Elves vs. Goblins" : "EVG",
        "Duel Decks: Garruk vs. Liliana" : "DDD",
        "Duel Decks: Heroes vs. Monsters" : "DDL",
        "Duel Decks: Izzet vs. Golgari" : "DDJ",
        "Duel Decks: Jace vs. Chandra" : "DD2",
        "Duel Decks: Jace vs. Vraska" : "DDM",
        "Duel Decks: Knights vs. Dragons" : "DDG",
        "Duel Decks: Phyrexia vs. the Coalition" : "DDE",
        "Duel Decks: Sorin vs. Tibalt" : "DDK",
        "Duel Decks: Speed vs. Cunning" : "DDN",
        "Duel Decks: Venser vs. Koth" : "DDI",
        "Duel Decks: Zendikar vs. Eldrazi" : "DDP",
        "Duels of the Planeswalkers" : "DPA",
        "Eighth Edition" : "8ED",
        "European Land Program" : "pELP",
        "Eventide" : "EVE",
        "Exodus" : "EXO",
        "Fallen Empires" : "FEM",
        "Fate Reforged" : "FRF",
        "Fifth Dawn" : "5DN",
        "Fifth Edition" : "5ED",
        "Fourth Edition" : "4ED",
        "Friday Night Magic" : "pFNM",
        "From the Vault: Angels" : "V15",
        "From the Vault: Annihilation (2014)" : "V14",
        "From the Vault: Dragons" : "DRB",
        "From the Vault: Exiled" : "V09",
        "From the Vault: Legends" : "V11",
        "From the Vault: Realms" : "V12",
        "From the Vault: Relics" : "V10",
        "From the Vault: Twenty" : "V13",
        "Future Sight" : "FUT",
        "Gatecrash" : "GTC",
        "Gateway" : "pGTW",
        "Grand Prix" : "pGPX",
        "Guildpact" : "GPT",
        "Guru" : "pGRU",
        "Happy Holidays" : "pHHO",
        "Homelands" : "HML",
        "Ice Age" : "ICE",
        "Innistrad" : "ISD",
        "International Collector's Edition" : "CEI",
        "Introductory Two-Player Set" : "ITP",
        "Invasion" : "INV",
        "Journey into Nyx" : "JOU",
        "Judge Gift Program" : "pJGP",
        "Judgment" : "JUD",
        "Khans of Tarkir" : "KTK",
        "Launch Parties" : "pLPA",
        "Legend Membership" : "pLGM",
        "Legends" : "LEG",
        "Legions" : "LGN",
        "Limited Edition Alpha" : "LEA",
        "Limited Edition Beta" : "LEB",
        "Lorwyn" : "LRW",
        "Magic 2010" : "M10",
        "Magic 2011" : "M11",
        "Magic 2012" : "M12",
        "Magic 2013" : "M13",
        "Magic 2014 Core Set" : "M14",
        "Magic 2015 Core Set" : "M15",
        "Magic Game Day" : "pMGD",
        "Magic Origins" : "ORI",
        "Magic Player Rewards" : "pMPR",
        "Magic: The Gathering-Commander" : "CMD",
        "Magic: The Gathering—Conspiracy" : "CNS",
        "Masters Edition" : "MED",
        "Masters Edition II" : "ME2",
        "Masters Edition III" : "ME3",
        "Masters Edition IV" : "ME4",
        "Media Inserts" : "pMEI",
        "Mercadian Masques" : "MMQ",
        "Mirage" : "MIR",
        "Mirrodin" : "MRD",
        "Mirrodin Besieged" : "MBS",
        "Modern Event Deck 2014" : "MD1",
        "Modern Masters" : "MMA",
        "Modern Masters 2015 Edition" : "MM2",
        "Morningtide" : "MOR",
        "Multiverse Gift Box" : "MGB",
        "Nemesis" : "NMS",
        "New Phyrexia" : "NPH",
        "Ninth Edition" : "9ED",
        "Odyssey" : "ODY",
        "Onslaught" : "ONS",
        "Planar Chaos" : "PLC",
        "Planechase" : "HOP",
        "Planechase 2012 Edition" : "PC2",
        "Planeshift" : "PLS",
        "Portal" : "POR",
        "Portal Demo Game" : "pPOD",
        "Portal Second Age" : "PO2",
        "Portal Three Kingdoms" : "PTK",
        "Premium Deck Series: Fire and Lightning" : "PD2",
        "Premium Deck Series: Graveborn" : "PD3",
        "Premium Deck Series: Slivers" : "H09",
        "Prerelease Events" : "pPRE",
        "Prophecy" : "PCY",
        "Pro Tour" : "pPRO",
        "Ravnica: City of Guilds" : "RAV",
        "Release Events" : "pREL",
        "Return to Ravnica" : "RTR",
        "Revised Edition" : "3ED",
        "Rise of the Eldrazi" : "ROE",
        "Rivals Quick Start Set" : "RQS",
        "Saviors of Kamigawa" : "SOK",
        "Scars of Mirrodin" : "SOM",
        "Scourge" : "SCG",
        "Seventh Edition" : "7ED",
        "Shadowmoor" : "SHM",
        "Shards of Alara" : "ALA",
        "Starter 1999" : "S99",
        "Starter 2000" : "S00",
        "Stronghold" : "STH",
        "Summer of Magic" : "pSUM",
        "Super Series" : "pSUS",
        "Tempest" : "TMP",
        "Tempest Remastered" : "TPR",
        "Tenth Edition" : "10E",
        "The Dark" : "DRK",
        "Theros" : "THS",
        "Time Spiral" : "TSP",
        "Time Spiral 'Timeshifted'" : "TSB",
        "Torment" : "TOR",
        "Two-Headed Giant Tournament" : "p2HG",
        "Ugin's Fate promos" : "FRF_UGIN",
        "Unglued" : "UGL",
        "Unhinged" : "UNH",
        "Unlimited Edition" : "2ED",
        "Urza's Destiny" : "UDS",
        "Urza's Legacy" : "ULG",
        "Urza's Saga" : "USG",
        "Vanguard" : "VAN",
        "Vintage Masters" : "VMA",
        "Visions" : "VIS",
        "Weatherlight" : "WTH",
        "Wizards of the Coast Online Store" : "pWOS",
        "World Magic Cup Qualifiers" : "pWCQ",
        "Worlds" : "pWOR",
        "Worldwake" : "WWK",
        "WPN and Gateway" : "pWPN",
        "Zendikar" : "ZEN",
        "Zendikar Expedition" : "EXP"
        ].sort { $0.0 < $1.0 }
    
    public static let rarities: [String] = [
        "-",
        "common",
        "uncommon",
        "rare",
        "mythic"
    ]
    
    public static let colors: [String] = [
        "-",
        "black",
        "blue",
        "green",
        "red",
        "white"
    ]
    
    public static let multicolor: [String] = [
        "-",
        "true",
        "false"
    ]
    
    public static let formats: [String] = [
        "-",
        "commander",
        "legacy",
        "vintage",
        "standard",
        "modern"
    ]
    
    public static let statuses: [String] = [
        "-",
        "legal",
        "restricted",
        "banned"
    ]
}